baseurl = "https://verummeum.com/"
title = "Verummeum"
languageCode = "en-us"
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 5

enableRobotsTXT = true

[author]
  homepage = "https://verummeum.com/"
  name = "Philip Vissenaekens"


[menu]

# Main menu

[[menu.main]]
    name = "blog"
    url  = "/blog/"
    weight = 1
    pre = ""

[[menu.main]]
    name = "art"
    url  = "/art/"
    weight = 2
    pre = ""

[[menu.main]]
    name = "search"
    url  = "/search/"
    weight = 3
    pre = "<i class='fas fa-search'></i>"

[params]
    defaultDescription = "Read articles about software development, open-source projects and gaming, with a focus on the Linux operating system."
    mainSections = ["blog", "art"]


    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contact@verummeum.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"

[Permalinks]
    blog = "/:filename/"
    art = "/:filename/"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  blog = ["HTML", "JSON", "RSS"]
  art = ["HTML", "JSON", "RSS"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false