baseurl = "https://verummeum.com/"
title = "Verummeum"
languageCode = "en-us"
defaultContentLanguage = "en"
# Disqus shortname
disqusShortname = ""
# Google Analytics tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 5

enableRobotsTXT = true

[author]
  homepage = "https://verummeum.com/"
  name = "Philip Vissenaekens"


[menu]

# Main menu

#[[menu.main]]
#    name = "blog"
#    url  = "/blog/"
#    weight = 1
#    pre = ""

[[menu.main]]
    name = "search"
    url  = "/search/"
    weight = 2
    pre = "<i class='fas fa-search'></i>"

[params]
    defaultDescription = "Read articles about software development, open-source projects and privacy, with a focus on the Linux operating system."
    mainSections = ["blog"]

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

[Permalinks]
    blog = "/:filename/"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  blog = ["HTML", "JSON", "RSS"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false